### ISSUE TITLE
EPIC - Build and test teams integration

### ISSUE THREAD

**Issue by AndreasThinks** [i-dot-ai/caddy-chatbot#170]
We need to build and test our teams integration robustly:

- [X] Build teams implementation #38 
- [ ] Robustly test and iterate
- [ ] Package, document and deploy as an app if appropriate
- [ ] Optional, ask MS to do a peer review for us

**Comment by AndreasThinks** [comment]
Add a ticket to this for adding this to teh dashboard (so how many users we have from teams vs google on an LCA by LCA basis)
